const ITEMS=[
"I worry too much about different things.","I try hard not to think about it or avoid situations that remind me of it.","I fear embarrassment.","I feel nervous, anxious, or on edge, especially around certain people.","I feel afraid as if something awful might happen.","I have nightmares about the experience or think about it when I do not want to.","I have trouble relaxing.","I feel numb or detached from others, activities, or my surroundings.","I avoid activities in which I am the center of attention, such as parties, meetings, or answering questions in class.","I cannot stop or control my worrying.","Being embarrassed or looking stupid is one of my worst fears.","I become easily annoyed or irritable.","I feel constantly on guard, watchful, or easily startled, especially around certain people or places.","I feel so restless that it is hard to sit still.","I feel the world is an unsafe place.","In social situations I feel a rush of intense discomfort and may notice my heart pounding, muscles tense up, or sweating.","I feel isolated and set apart from others.","I avoid certain situations or speaking to certain people.","If I think about past experiences of discrimination, I cannot control my emotions.","I am nervous in social situations and afraid people will notice sweating, blushing, or trembling.","Fear of social situations causes a lot of problems in my daily functioning."
];
const OPTIONS=[{label:"Never",value:1},{label:"Rarely",value:2},{label:"Sometimes",value:3},{label:"Often",value:4}];
const TYPES=["Racial/Ethnic","Gender","Sexual orientation","Social class","Religion","Age","Disability","Other"];
let answers=Array(21).fill(1),types={};const $=id=>document.getElementById(id);const sum=(a,b)=>a+b;
function reset(){answers=Array(21).fill(1);types={};render()}
function render(){$("questions").innerHTML=ITEMS.map((text,i)=>`<section class="card question-card"><h2><span class="question-number">${i+1}.</span>${i===18?text:`Due to past experiences of discrimination, ${lowerFirst(text)}`}</h2><div class="response-grid">${OPTIONS.map(o=>`<label class="response-option"><input type="radio" name="item-${i}" value="${o.value}" ${answers[i]===o.value?"checked":""}><span>${o.label}<br>${o.value}</span></label>`).join("")}</div></section>`).join("");document.querySelectorAll('[name^="item-"]').forEach(x=>x.onchange=()=>{answers[+x.name.split("-")[1]]=+x.value;update()});renderTypes();update()}
function renderTypes(){$("type-grid").innerHTML=TYPES.map(type=>{const v=types[type]||{selected:false,percent:0,text:""};return`<div class="type-row"><input type="checkbox" data-type-check="${type}" ${v.selected?"checked":""}>${type==="Other"?`<input type="text" data-type-text="Other" value="${escapeAttr(v.text)}" placeholder="Other type">`:`<span>${type}</span>`}<label><input type="number" min="0" max="100" step="1" data-type-percent="${type}" value="${v.percent}" ${v.selected?"":"disabled"}>%</label></div>`}).join("");document.querySelectorAll("[data-type-check]").forEach(x=>x.onchange=()=>{const v=types[x.dataset.typeCheck]||{percent:0,text:""};v.selected=x.checked;types[x.dataset.typeCheck]=v;renderTypes();update()});document.querySelectorAll("[data-type-percent]").forEach(x=>x.oninput=()=>{const v=types[x.dataset.typePercent]||{selected:true,text:""};v.percent=Math.min(100,Math.max(0,+x.value||0));types[x.dataset.typePercent]=v;update()});document.querySelectorAll("[data-type-text]").forEach(x=>x.oninput=()=>{const v=types.Other||{selected:true,percent:0};v.text=x.value;types.Other=v;update()})}
function update(){const total=answers.reduce(sum,0),avg=total/21,nearest=OPTIONS.reduce((best,o)=>Math.abs(o.value-avg)<Math.abs(best.value-avg)?o:best);$("score-display").textContent=`${total} / 84`;$("average-display").textContent=`${avg.toFixed(2)} - ${nearest.label}`;const counts=OPTIONS.map(o=>answers.filter(v=>v===o.value).length);$("distribution").innerHTML=OPTIONS.map((o,i)=>`<div><span class="small-label">${o.label}</span><strong>${counts[i]} item${counts[i]===1?"":"s"}</strong></div>`).join("");const pct=selectedTypes().reduce((n,x)=>n+x.percent,0);$("percentage-status").textContent=selectedTypes().length?`Selected percentages total ${pct}%.${pct===100?"":" Adjust to 100% when the client can reasonably estimate the distribution."}`:"No discrimination types selected.";const detailed=document.querySelector('[name="outputStyle"]:checked').value==="detailed";$("output").value=detailed?detail(total,avg):summary(total,avg,counts)}
function selectedTypes(){return Object.entries(types).filter(([,v])=>v.selected).map(([name,v])=>({name:name==="Other"&&v.text?.trim()?v.text.trim():name,percent:v.percent||0}))}
function summary(total,avg,counts){const sources=selectedTypes();return`TSDS completed with a total score of ${total}/84 and an average item response of ${avg.toFixed(2)}/4. Responses included ${counts[0]} Never, ${counts[1]} Rarely, ${counts[2]} Sometimes, and ${counts[3]} Often endorsements. ${sources.length?`Reported discrimination attributions were ${sources.map(x=>`${x.name} (${x.percent}%)`).join(", ")}.`:"No discrimination attributions were documented."} Higher scores indicate more frequent discrimination-related trauma symptoms; the TSDS does not have an established diagnostic cutoff.`}
function detail(total,avg){const lines=["Trauma Symptoms of Discrimination Scale (TSDS)",""];ITEMS.forEach((text,i)=>lines.push(`${i+1}. ${text}`,`${OPTIONS.find(o=>o.value===answers[i]).label} - ${answers[i]}`,""));lines.push(`Total: ${total} / 84`,`Average response: ${avg.toFixed(2)} / 4`,"","Types of Discrimination");const sources=selectedTypes();lines.push(...(sources.length?sources.map(x=>`${x.name}: ${x.percent}%`):["None documented"]),"","Interpretation","Higher scores indicate more frequent discrimination-related trauma symptoms. No diagnostic cutoff is established.");return lines.join("\n")}
function lowerFirst(s){return s.charAt(0).toLowerCase()+s.slice(1)}function escapeAttr(s=""){return String(s).replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;")}
$("reset-button").onclick=reset;document.querySelectorAll('[name="outputStyle"]').forEach(x=>x.onchange=update);$("copy-button").onclick=async()=>{await navigator.clipboard.writeText($("output").value);$("copy-status").textContent="Copied";setTimeout(()=>$("copy-status").textContent="",1500)};$("select-button").onclick=()=>{$("output").focus();$("output").select()};reset();
